CREATE TABLE finished_product_batches (
    id                  CHAR(36)        NOT NULL PRIMARY KEY,
    tenant_id           CHAR(36)        NOT NULL,
    batch_number        VARCHAR(30)     NOT NULL,
    product_id          CHAR(36)        NOT NULL,
    quantity            DECIMAL(10,2)   NOT NULL,
    unit                VARCHAR(50)     NOT NULL,
    blend_date          DATE            NOT NULL,
    status              ENUM('PENDING','IN_PROGRESS','PASSED','FAILED') NOT NULL DEFAULT 'PENDING',
    appearance          VARCHAR(50)     NULL,
    color_ok            TINYINT(1)      NULL,
    odor                VARCHAR(50)     NULL,
    ph                  DECIMAL(5,2)    NULL,
    specific_gravity    DECIMAL(6,4)    NULL,
    notes               TEXT            NULL,
    tested_by_id        CHAR(36)        NULL,
    tested_at           DATETIME        NULL,
    warehouse_id        CHAR(36)        NULL,
    moved_to_warehouse  TINYINT(1)      NOT NULL DEFAULT 0,
    moved_at            DATETIME        NULL,
    is_deleted          TINYINT(1)      NOT NULL DEFAULT 0,
    created_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by          CHAR(36)        NULL,
    INDEX idx_fpb_tenant  (tenant_id),
    INDEX idx_fpb_status  (status),
    INDEX idx_fpb_product (product_id)
);
